"""Rule source definitions and the pinned lock file.

``sources.yaml`` (human-edited) says *where* rules come from. ``lock/rules.lock``
(generated by :func:`refresh_lock`, committed) says *exactly which bytes*: a
release tag or commit SHA per source, the archive SHA-256, and a per-file
SHA-256 manifest in ``lock/manifests/<source>.json``.

Both files ship inside the Python package, so the integrity reference used at
scan time lives with the code, not next to the rules it checks.
"""

from __future__ import annotations

import hashlib
import io
import json
import os
import urllib.request
import zipfile
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path, PurePosixPath
from typing import Literal

import structlog
import yaml
from pydantic import BaseModel, Field

log = structlog.get_logger(component="rules.lock")

PACKAGE_DIR = Path(__file__).parent
SOURCES_FILE = PACKAGE_DIR / "sources.yaml"
LOCK_DIR = PACKAGE_DIR / "lock"
LOCK_FILE = LOCK_DIR / "rules.lock"
PROFILES = ("precise", "broad")
ENGINES = ("yara", "sigma")

Fetcher = Callable[[str], bytes]


class RuleIntegrityError(RuntimeError):
    """Raised when rules do not match the pinned lock."""


class RuleSource(BaseModel):
    """One upstream rule source, as declared in sources.yaml."""

    id: str
    engine: Literal["yara", "sigma"]
    repo: str
    kind: Literal["release", "branch"]
    asset: str | None = None  # release asset name
    branch: str | None = None  # branch resolved to a commit at lock time
    path_filter: str = ""  # keep only files under this path (after the archive root)
    extensions: list[str] = Field(default_factory=list)
    exclude: list[str] = Field(default_factory=list)  # path substrings to drop
    profiles: list[Literal["precise", "broad"]] = Field(default_factory=list)
    # SPDX id; declared here when GitHub cannot detect it (NOASSERTION)
    license: str | None = None


class LockedSource(RuleSource):
    """A source pinned to exact bytes."""

    ref: str  # release tag or commit SHA
    url: str
    archive_sha256: str
    files: int = 0


class RuleLock(BaseModel):
    """The whole lock file."""

    version: int = 1
    generated_at: str = ""
    sources: list[LockedSource] = Field(default_factory=list)

    def get(self, source_id: str) -> LockedSource:
        for source in self.sources:
            if source.id == source_id:
                return source
        raise KeyError(source_id)

    def for_profile(self, profile: str, engine: str | None = None) -> list[LockedSource]:
        """Sources of a profile, in precedence (lock) order."""
        if profile not in PROFILES:
            raise ValueError(f"Unknown rule profile '{profile}'. Use one of: {', '.join(PROFILES)}")
        return [
            s for s in self.sources
            if profile in s.profiles and (engine is None or s.engine == engine)
        ]


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def load_sources(path: Path = SOURCES_FILE) -> list[RuleSource]:
    data = yaml.safe_load(path.read_text()) or {}
    return [RuleSource(**s) for s in data.get("sources", [])]


def load_lock(lock_dir: Path = LOCK_DIR) -> RuleLock:
    lock_file = lock_dir / "rules.lock"
    if not lock_file.exists():
        raise RuleIntegrityError(
            f"No rule lock at {lock_file}. Generate it with: defair rules lock --refresh"
        )
    return RuleLock(**(yaml.safe_load(lock_file.read_text()) or {}))


def load_manifest(source_id: str, lock_dir: Path = LOCK_DIR) -> dict[str, str]:
    """Per-file SHA-256 manifest of a source: {relative path: sha256}."""
    path = lock_dir / "manifests" / f"{source_id}.json"
    if not path.exists():
        raise RuleIntegrityError(f"Missing manifest for rule source '{source_id}': {path}")
    return json.loads(path.read_text())


# ---------------------------------------------------------------------------
# Archive handling (shared with sync)
# ---------------------------------------------------------------------------


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def select_members(archive: zipfile.ZipFile, source: RuleSource) -> list[tuple[str, str]]:
    """Pick the rule files of a source out of its archive.

    Returns ``(member name, relative path)`` pairs. GitHub commit archives wrap
    everything in a ``<repo>-<sha>/`` folder, which is stripped. The upstream
    tree is otherwise preserved — no flattening, so same-named files in
    different folders never collide.

    Raises:
        RuleIntegrityError: On absolute or ``..`` member paths (zip slip).
    """
    selected = []
    extensions = tuple(e.lower() for e in source.extensions)
    for info in archive.infolist():
        if info.is_dir():
            continue
        member = PurePosixPath(info.filename)
        if member.is_absolute() or ".." in member.parts:
            raise RuleIntegrityError(f"Unsafe path in {source.id} archive: {info.filename}")
        parts = member.parts[1:] if source.kind == "branch" else member.parts
        if not parts:
            continue
        rel = "/".join(parts)
        if source.path_filter and not rel.startswith(source.path_filter):
            continue
        if any(ex in rel for ex in source.exclude):
            continue
        if extensions and not rel.lower().endswith(extensions):
            continue
        selected.append((info.filename, rel))
    return sorted(selected, key=lambda pair: pair[1])


def build_manifest(data: bytes, source: RuleSource) -> dict[str, str]:
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        return {
            rel: sha256_bytes(archive.read(member))
            for member, rel in select_members(archive, source)
        }


# ---------------------------------------------------------------------------
# Network (lock refresh + sync)
# ---------------------------------------------------------------------------


def http_get(url: str) -> bytes:
    """GET a URL; uses GITHUB_TOKEN for api.github.com when set."""
    headers = {"User-Agent": "defair-rules"}
    token = os.environ.get("GITHUB_TOKEN")
    if token and url.startswith("https://api.github.com/"):
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request(url, headers=headers)
    if not url.startswith("https://"):
        raise ValueError(f"Refusing non-HTTPS URL: {url}")
    with urllib.request.urlopen(request, timeout=300) as response:
        return response.read()


def _api(path: str, fetch: Fetcher) -> dict:
    return json.loads(fetch(f"https://api.github.com/{path}"))


def resolve_source(source: RuleSource, fetch: Fetcher = http_get) -> tuple[str, str, str | None]:
    """Resolve a source to ``(ref, archive url, expected sha256 or None)``."""
    if source.kind == "release":
        release = _api(f"repos/{source.repo}/releases/latest", fetch)
        for asset in release.get("assets", []):
            if asset["name"] == source.asset:
                digest = asset.get("digest") or ""
                expected = digest.removeprefix("sha256:") if digest.startswith("sha256:") else None
                return release["tag_name"], asset["browser_download_url"], expected
        raise RuleIntegrityError(
            f"Release {release.get('tag_name')} of {source.repo} has no asset '{source.asset}'"
        )
    commit = _api(f"repos/{source.repo}/commits/{source.branch}", fetch)
    sha = commit["sha"]
    return sha, f"https://github.com/{source.repo}/archive/{sha}.zip", None


def refresh_lock(
    sources: list[RuleSource] | None = None,
    lock_dir: Path = LOCK_DIR,
    fetch: Fetcher = http_get,
) -> RuleLock:
    """Resolve every source to its newest release/commit and rewrite the lock.

    Release archives are checked against the digest GitHub publishes. A lock
    bump is meant to be reviewed and committed like any other change.
    """
    sources = sources if sources is not None else load_sources()
    (lock_dir / "manifests").mkdir(parents=True, exist_ok=True)
    locked: list[LockedSource] = []

    for source in sources:
        ref, url, expected = resolve_source(source, fetch)
        data = fetch(url)
        digest = sha256_bytes(data)
        if expected and digest != expected:
            raise RuleIntegrityError(
                f"{source.id}: archive SHA-256 {digest} differs from GitHub digest {expected}"
            )
        manifest = build_manifest(data, source)
        if not manifest:
            raise RuleIntegrityError(f"{source.id}: no rule file matched in {url}")
        license_id = source.license
        if not license_id:
            try:
                repo_license = _api(f"repos/{source.repo}", fetch).get("license") or {}
                license_id = repo_license.get("spdx_id")
            except Exception:  # noqa: BLE001 — license lookup is informational
                license_id = None

        (lock_dir / "manifests" / f"{source.id}.json").write_text(
            json.dumps(manifest, indent=1, sort_keys=True) + "\n"
        )
        locked.append(LockedSource(
            **(source.model_dump() | {"license": license_id}),
            ref=ref, url=url, archive_sha256=digest, files=len(manifest),
        ))
        log.info("rule_source_locked", source=source.id, ref=ref, files=len(manifest))

    lock = RuleLock(generated_at=datetime.now(UTC).isoformat(), sources=locked)
    header = (
        "# Generated by `defair rules lock --refresh` — do not edit by hand.\n"
        "# Pins every rule source to exact bytes; see sources.yaml.\n"
    )
    (lock_dir / "rules.lock").write_text(
        header + yaml.safe_dump(lock.model_dump(), sort_keys=False, allow_unicode=True)
    )
    return lock
